### ISSUE TITLE
Provide a configuration

### ISSUE THREAD

**Issue by EmanueleMinotto** [adespresso/FeatureBundle#21]
The initial default configuration could be:

``` yml
ae_feature:
    admin:
        enabled: true
        group:   Application
        label:   Features
    cache:
        enabled: true
        timeout: 86400
```

**Attention:** considering the minor change, the default configuration should act as the current behaviour.
