### ISSUE TITLE
Include a cache warmer

### ISSUE THREAD

**Issue by EmanueleMinotto** [adespresso/FeatureBundle#22]
Depends on https://github.com/adespresso/FeatureBundle/issues/21

Add a [cache warmer](http://symfony.com/doc/current/reference/dic_tags.html#kernel-cache-warmer), enabled by default, to fetch all the features before the user invokation.

Configuration:

``` yml
ae_feature:
    cache:
        preload_on_warmup: true
```
